In [7]:
import torch

In [8]:
import torch
torch.cuda.is_available()

True

In [9]:
scaler = torch.tensor (8)

In [10]:
scaler
scaler.ndim

0

In [11]:
vector = torch.tensor([7,7])

In [12]:
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [15]:
vector = torch.tensor ([1,2,3,4,5])

In [16]:
vector

tensor([1, 2, 3, 4, 5])

In [17]:
vector.ndim

1

In [18]:
vector.shape

torch.Size([5])

In [20]:
vector = torch.tensor ([1,2,3])

In [ ]:
# 1. 

In [22]:
float_32_tensor = torch.tensor([1.0,2.0,3.0])

In [21]:
vector.ndim

1

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
float_64_tensor = torch.tensor([1.0,2.0,3.0],dtype=torch.float64)
float_64_tensor.dtype

torch.float64

In [ ]:
# 2. check the device of the tensor vector

In [25]:
tensor1 = torch.tensor([1,2])

In [26]:
tensor1.device

device(type='cpu')

In [27]:
tensor2 = torch.tensor([1,2,3], device = 'cuda:0')

In [28]:
tensor2.device

device(type='cuda', index=0)

In [ ]:
# torch tensor add, subtraction, multiplication, division

3. Reshaping, viewing, and stacking

In [90]:
y = torch.arange (1., 10.)
y

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [91]:
x = torch.tensor ([1,2,3,4,5,6,7,8,9])
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
x + y

tensor([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [93]:
x - y

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [94]:
z = x-y+x+x+y
z

tensor([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [95]:
x * y

tensor([ 1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

In [96]:
x/y

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [97]:
i = 2
i

2

In [98]:
x/i

tensor([0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000])

In [99]:
y/i

tensor([0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000])

In [100]:
j=3

In [101]:
x/j

tensor([0.3333, 0.6667, 1.0000, 1.3333, 1.6667, 2.0000, 2.3333, 2.6667, 3.0000])

In [102]:
a = 4
a

4

In [103]:
z/i

tensor([ 1.5000,  3.0000,  4.5000,  6.0000,  7.5000,  9.0000, 10.5000, 12.0000,
        13.5000])

In [104]:
y

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [105]:
y.shape

torch.Size([9])

In [108]:
#reshape: reshape the tensor into a defined shape
y_reshaped = y.reshape(1,9)
y_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [109]:
y_reshaped.dtype

torch.float32

In [110]:
y_reshaped2 = y.reshape(3,3)
y_reshaped2

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [111]:
y_reshaped2.shape

torch.Size([3, 3])

In [112]:
zz = y.view(1,9)
zz.shape

torch.Size([1, 9])

# DIFFERENCE BETWEEN numpy array & torch tensor!

In [119]:
!pip install numpy
import numpy as np
import torch

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 39.2 MB/s eta 0:00:00m eta 0:00:010:00:01

[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: pip install --upgrade pip


In [123]:
numpy_arr = np.arange (0,10)
tensor = torch.arange (0,10)

In [124]:
tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
#1 data type
numpy_arr.dtype

dtype('int64')

In [126]:
tensor.dtype

torch.int64

In [130]:
#2 new data
torch.zeros(4,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [129]:
array_zero = np.zeros ((4,4))
array_zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [131]:
#3 multiplication
# numpy & torch tensor have the same format for multiplication

# 3.1 element-wise
# 3.2 

In [138]:
#4 new data 
torch.ones (3,3,3,3)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])