In [7]:
import torch

In [8]:
import torch
torch.cuda.is_available()

True

In [9]:
scaler = torch.tensor (8)

In [10]:
scaler
scaler.ndim

0

In [11]:
vector = torch.tensor([7,7])

In [12]:
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [15]:
vector = torch.tensor ([1,2,3,4,5])

In [16]:
vector

tensor([1, 2, 3, 4, 5])

In [17]:
vector.ndim

1

In [18]:
vector.shape

torch.Size([5])

In [20]:
vector = torch.tensor ([1,2,3])

In [ ]:
# 1. 

In [22]:
float_32_tensor = torch.tensor([1.0,2.0,3.0])

In [21]:
vector.ndim

1

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
float_64_tensor = torch.tensor([1.0,2.0,3.0],dtype=torch.float64)
float_64_tensor.dtype

torch.float64

In [ ]:
# 2. check the device of the tensor vector

In [25]:
tensor1 = torch.tensor([1,2])

In [26]:
tensor1.device

device(type='cpu')

In [27]:
tensor2 = torch.tensor([1,2,3], device = 'cuda:0')

In [28]:
tensor2.device

device(type='cuda', index=0)

In [ ]:
# torch tensor add, subtraction, multiplication, division

3. Reshaping, viewing, and stacking

In [35]:
y = torch.arange (1., 10.)
y

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [37]:
x = torch.tensor ([1,2,3,4,5,6,7,8,9])
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
x + y

tensor([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [38]:
x - y

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
z = x-y+x+x+y
z

tensor([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [42]:
x * y

tensor([ 1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

In [43]:
x/y

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
i = 2
i

2

In [45]:
x/i

tensor([0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000])

In [46]:
y/i

tensor([0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000])

In [47]:
j=3

In [48]:
x/j

tensor([0.3333, 0.6667, 1.0000, 1.3333, 1.6667, 2.0000, 2.3333, 2.6667, 3.0000])